### ISSUE TITLE
Can't connect a Hori Fighting Commander 4

### ISSUE THREAD

**Issue by meowfaceman** [nefarius/ScpToolkit#232]
I get the following message when trying to use a Hori Fighting Commander 4:

```
<log4j:event logger="ScpControl.ScpHub" timestamp="1457234890216" level="ERROR" thread="6"><log4j:message>Unexpected error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ScpControl.RootHub.OnDeviceArrival(Object sender, ArrivalEventArgs e)
   at ScpControl.ScpHub.OnDeviceArrival(Object sender, ArrivalEventArgs e)
   at ScpControl.ScpHub.LogArrival(IDsDevice Arrived)
   at ScpControl.Usb.UsbHub.Start()</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="OCT" /><log4j:data name="log4japp" value="ScpService.exe" /><log4j:data name="log4net:UserName" value="NT AUTHORITY\SYSTEM" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="OCT" /></log4j:properties><log4j:locationInfo class="ScpControl.Usb.UsbHub" method="Start" file="" line="0" /></log4j:event>
```

You can flip the controller between PS3 and PS4 mode, and I've had little luck switching between the two. I'll tinker a bit more in the meanwhile.

**Comment by Jan200101** [comment]
I think controllers that support both arent supported they should be but the pc trys handling the PS3 mode as PS3 and PS4 ; and the PS4 mode as PS4 and PS3.
Try using a service that only supports one like DS4Windows
