### ISSUE TITLE
Can't run ScpDriverInstaller

### ISSUE THREAD

**Issue by TheKaNN** [nefarius/ScpToolkit#454]
Running ScpDriverInstaller gives me the error "a fatal error has occured. Consult the logs for details."

Happens regardless which version of ScpToolkit I use. Everything that is required is installed as well. 

Log is below and I've also submitted it as a pastebin if that's easier to read. http://pastebin.com/CnnRFn5X

`<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746210101" level="INFO" thread="1"><log4j:message>SCP Driver Installer 1.7.277.16103 [Built: 04/12/2016 17:58:01]</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="Window_Initialized" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs" line="580" /></log4j:event>
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746210125" level="INFO" thread="1"><log4j:message>Microsoft Windows 7 Home Premium (6.1.7601.65536 AMD64) detected</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" /></log4j:properties><log4j:locationInfo class="System.Windows.FrameworkElement" method="RaiseInitialized" file="" line="0" /></log4j:event>
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746210164" level="DEBUG" thread="1">log4j:messagePreparing to load libwdi/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="45" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746210167" level="DEBUG" thread="1">log4j:messageCalled from 64-Bit process/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="52" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746210167" level="DEBUG" thread="1">log4j:messagelibwdi path: F:\ScpToolkit\libwdi\amd64\libwdi.dll/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="57" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746210170" level="DEBUG" thread="1">log4j:messageLoaded library: F:\ScpToolkit\libwdi\amd64\libwdi.dll/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="64" />/log4j:event
<log4j:event logger="ScpDriverInstaller.App" timestamp="1474746210179" level="FATAL" thread="1">log4j:messageAn unexpected error occured on application startup: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info) in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 120
   at ScpControl.Driver.WdiWrapper.get_UsbDeviceList() in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 97
   at ScpDriverInstaller.MainWindow.OnUsbDeviceAddedOrRemoved() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 0
   at ScpControl.Usb.PnP.UsbNotifier.RegisterHandle(IntPtr handle) in d:\Development\C#\ScpServer\Source\ScpControl\Usb\PnP\UsbNotifier.cs:line 93
   at ScpDriverInstaller.MainWindow.OnSourceInitialized(EventArgs e) in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 648
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScpDriverInstaller.App.Main() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\obj\Release\App.g.cs:line 0/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpDriverInstaller.App" method="&lt;OnStartup&gt;b__0" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\App.xaml.cs" line="19" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746210245" level="INFO" thread="1">log4j:messageSCP DSx Service stopped/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="Window_Loaded" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs" line="611" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746211011" level="FATAL" thread="1">log4j:messageAn unexpected exception occurred: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info) in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 120
   at ScpControl.Driver.WdiWrapper.get_UsbDeviceList() in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 97
   at ScpDriverInstaller.MainWindow.OnUsbDeviceAddedOrRemoved() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 0
   at ScpControl.Usb.PnP.UsbNotifier.RegisterHandle(IntPtr handle) in d:\Development\C#\ScpServer\Source\ScpControl\Usb\PnP\UsbNotifier.cs:line 93
   at ScpDriverInstaller.MainWindow.OnSourceInitialized(EventArgs e) in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 648
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScpDriverInstaller.App.Main() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\obj\Release\App.g.cs:line 0/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="System.Runtime.InteropServices.Marshal" method="ReadByte" file="" line="0" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746231548" level="INFO" thread="1">log4j:messageSCP Driver Installer 1.7.277.16103 [Built: 04/12/2016 17:58:01]/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="Window_Initialized" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs" line="580" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746231556" level="INFO" thread="1">log4j:messageMicrosoft Windows 7 Home Premium (6.1.7601.65536 AMD64) detected/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="System.Windows.FrameworkElement" method="RaiseInitialized" file="" line="0" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746231588" level="DEBUG" thread="1">log4j:messagePreparing to load libwdi/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="45" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746231590" level="DEBUG" thread="1">log4j:messageCalled from 64-Bit process/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="52" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746231590" level="DEBUG" thread="1">log4j:messagelibwdi path: F:\ScpToolkit\libwdi\amd64\libwdi.dll/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="57" />/log4j:event
<log4j:event logger="ScpControl.Driver.NativeLibraryWrapper`1" timestamp="1474746231592" level="DEBUG" thread="1">log4j:messageLoaded library: F:\ScpToolkit\libwdi\amd64\libwdi.dll/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpControl.Driver.NativeLibraryWrapper`1" method="LoadNativeLibrary" file="d:\Development\C#\ScpServer\Source\ScpControl\Driver\NativeLibraryWrapper.cs" line="64" />/log4j:event
<log4j:event logger="ScpDriverInstaller.App" timestamp="1474746231597" level="FATAL" thread="1">log4j:messageAn unexpected error occured on application startup: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info) in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 120
   at ScpControl.Driver.WdiWrapper.get_UsbDeviceList() in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 97
   at ScpDriverInstaller.MainWindow.OnUsbDeviceAddedOrRemoved() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 0
   at ScpControl.Usb.PnP.UsbNotifier.RegisterHandle(IntPtr handle) in d:\Development\C#\ScpServer\Source\ScpControl\Usb\PnP\UsbNotifier.cs:line 93
   at ScpDriverInstaller.MainWindow.OnSourceInitialized(EventArgs e) in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 648
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScpDriverInstaller.App.Main() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\obj\Release\App.g.cs:line 0/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpDriverInstaller.App" method="&lt;OnStartup&gt;b__0" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\App.xaml.cs" line="19" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746231638" level="WARN" thread="1">log4j:messageService doesn't exist, maybe it was uninstalled before/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="ScpDriverInstaller.MainWindow" method="StopService" file="d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs" line="740" />/log4j:event
<log4j:event logger="ScpDriverInstaller.MainWindow" timestamp="1474746232623" level="FATAL" thread="1">log4j:messageAn unexpected exception occurred: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info) in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 120
   at ScpControl.Driver.WdiWrapper.get_UsbDeviceList() in d:\Development\C#\ScpServer\Source\ScpControl\Driver\WdiWrapper.cs:line 97
   at ScpDriverInstaller.MainWindow.OnUsbDeviceAddedOrRemoved() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 0
   at ScpControl.Usb.PnP.UsbNotifier.RegisterHandle(IntPtr handle) in d:\Development\C#\ScpServer\Source\ScpControl\Usb\PnP\UsbNotifier.cs:line 93
   at ScpDriverInstaller.MainWindow.OnSourceInitialized(EventArgs e) in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\MainWindow.xaml.cs:line 648
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScpDriverInstaller.App.Main() in d:\Development\C#\ScpServer\Source\ScpDriverInstaller\obj\Release\App.g.cs:line 0/log4j:messagelog4j:properties<log4j:data name="log4jmachinename" value="KaNN-DESKTOP" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="KaNN-DESKTOP\KaNN" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="KaNN-DESKTOP" />/log4j:properties<log4j:locationInfo class="System.Runtime.InteropServices.Marshal" method="ReadByte" file="" line="0" />/log4j:event
`

**Comment by AnonHax0r** [comment]
Bump Im getting the same, here is the error from the log `   at ScpDriverInstaller.App.Main()]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="DESKTOP-4DV8NRD" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="DESKTOP-4DV8NRD\Teddy" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="DESKTOP-4DV8NRD" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.App" method="&lt;OnStartup&gt;b__0" file="" line="0" /></log4j:event>
`
