### ISSUE TITLE
Memory Access Error from driver installer.

### ISSUE THREAD

**Issue by AnonHax0r** [nefarius/ScpToolkit#482]
The SCPtoolkit Driver installer fails NO MATTER WHAT and I had it previously working. Aniversary update is likely the cause. Here is the error log. Please help get me back to my controller.
`<log4j:event logger="ScpDriverInstaller.App" timestamp="1476868107136" level="FATAL" thread="1"><log4j:message><![CDATA[An unexpected error occured on application startup: System.Windows.Markup.XamlParseException: Initialization of 'ScpDriverInstaller.MainWindow' threw an exception. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info)
   at ScpControl.Driver.WdiWrapper.get_UsbDeviceList()
   at ScpDriverInstaller.MainWindow.Window_Initialized(Object sender, EventArgs e)
   at System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScpDriverInstaller.App.Main()]]></log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="DESKTOP-4DV8NRD" /><log4j:data name="log4japp" value="ScpDriverInstaller.exe" /><log4j:data name="log4net:UserName" value="DESKTOP-4DV8NRD\Teddy" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:HostName" value="DESKTOP-4DV8NRD" /></log4j:properties><log4j:locationInfo class="ScpDriverInstaller.App" method="&lt;OnStartup&gt;b__0" file="" line="0" /></log4j:event>`

**Comment by ncarrara** [comment]
Same here :

<log4j:event logger="ScpDriverInstaller.App" timestamp="1485646018164" level="FATAL" thread="1"><log4j:message><![CDATA[An unexpected error occured on application startup: System.Windows.Markup.XamlParseException: L'initialisation de 'ScpDriverInstaller.MainWindow' a levé une exception. ---> System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée.
   à System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   à ScpControl.Driver.WdiWrapper.NativeToManagedWdiUsbDevice(wdi_device_info info)
   à ScpControl.Driver.WdiWrapper.get_UsbDeviceList()
   à ScpDriverInstaller.MainWindow.Window_Initialized(Object sender, EventArgs e)
   à System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   à System.Windows.FrameworkElement.TryFireInitialized()
   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
