### ISSUE TITLE
Windows 8: NightHawk Pro X no longer works, blue screens on boot

### ISSUE THREAD

**Issue by glimlost** [nefarius/ScpToolkit#899]
During and after installing using this software I ran into several problems.
The driver installation hung for 20 minutes so I retried with the "Force Install" option and it worked and without the bluetooth option selected.
The system never recognized the controller I had connected so I rebooted.
After rebooting my keyboard didn't work and I heard a bunch of error noises from the system tray.
Looking at event viewer I found the following messages from the server application(ordered from newest to oldest):

Application 'C:\Program Files\Nefarius Software Solutions\ScpToolkit\ScpTrayApp.exe' (pid 6640) cannot be restarted - Application SID does not match Conductor SID..

Faulting application name: ScpService.exe, version: 1.6.238.16010, time stamp: 0x569253f6
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666, time stamp: 0x58f33794
Exception code: 0xe0434352
Fault offset: 0x00000000000095fc
Faulting process id: 0x588
Faulting application start time: 0x01d31ef550ee43b9
Faulting application path: C:\Program Files\Nefarius Software Solutions\ScpToolkit\ScpService.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 95a4a164-8ae8-11e7-828e-5cf3707c2f06
Faulting package full name: 
Faulting package-relative application ID: 

Application: ScpService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Buffer.BlockCopy(System.Array, Int32, System.Array, Int32, Int32)
   at ScpControl.Usb.Ds3.UsbDs3.Process(System.DateTime)
   at System.Reactive.AnonymousSafeObserver`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(Int64)
   at System.Reactive.Linq.ObservableImpl.Timer+TimerImpl.Tick(Int64)
   at System.Reactive.Concurrency.DefaultScheduler+<>c__DisplayClass9`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SchedulePeriodic>b__7()
   at System.Reactive.Concurrency.AsyncLock.Wait(System.Action)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

So I rebooted again both with a controller plugged in and not plugged in and got several BSODs(once again, newest to oldest):

{Registry Hive Recovered} Registry hive (file): '\??\C:\Users\<username>\ntuser.dat' was corrupted and it has been recovered. Some data might have been lost.

The SCP DSx Service service terminated unexpectedly.  It has done this 1 time(s).
Provider: Service Control Manager
Event data param 1 SCP DSx Service
Event data param 2 1 44007300330053006500720076006900630065000000

The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000001a (0x0000000000041793, 0xfffff6bffaf902f8, 0x0000000000000036, 0x0000000000000035). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: 082717-7718-01.

The SCP DSx Service service depends on the Scp Virtual Bus Driver service which failed to start because of the following error: 
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

The Scp Virtual Bus Driver service failed to start due to the following error: 
The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

After getting to a booted state I went ahead and ran the ScpToolkit_Setup.exe and selected the remove option and rebooted. My keyboard still does not work. I double checked the services that are installed and there is nothing involved with Scp. I double checked the program folder, only the driver, logs, and database folders were there(why is the driver not removed as part of the removal process?).

**Comment by glimlost** [comment]
Update: I plugged in my old Key Tronic USB keyboard, so it is not all USB keyboards on my computer that are broken.
